In [2]:
# Ce qu'il y a dans le repertoire de travail

In [3]:
from os import listdir

In [4]:
# Affichage des noms des fichiers textes
noms_fichiers = listdir("Speeches")
noms_fichiers

['BattleCreekDec19_2019.txt',
 'BemidjiSep18_2020.txt',
 'CharlestonFeb28_2020.txt',
 'CharlotteMar2_2020.txt',
 'CincinnatiAug1_2019.txt',
 'ColoradorSpringsFeb20_2020.txt',
 'DallasOct17_2019.txt',
 'DesMoinesJan30_2020.txt',
 'FayettevilleSep19_2020.txt',
 'FayettevilleSep9_2019.txt',
 'FreelandSep10_2020.txt',
 'GreenvilleJul17_2019.txt',
 'HendersonSep13_2020.txt',
 'HersheyDec10_2019.txt',
 'LasVegasFeb21_2020.txt',
 'LatrobeSep3_2020.txt',
 'LexingtonNov4_2019.txt',
 'MilwaukeeJan14_2020.txt',
 'MindenSep12_2020.txt',
 'MinneapolisOct10_2019.txt',
 'MosineeSep17_2020.txt',
 'NewHampshireAug15_2019.txt',
 'NewHampshireAug28_2020.txt',
 'NewHampshireFeb10_2020.txt',
 'NewMexicoSep16_2019.txt',
 'OhioSep21_2020.txt',
 'PhoenixFeb19_2020.txt',
 'PittsburghSep22_2020.txt',
 'TexasSep23_2019.txt',
 'ToledoJan9_2020.txt',
 'TulsaJun20_2020.txt',
 'TupeloNov1_2019.txt',
 'WildwoodJan28_2020.txt',
 'Winston-SalemSep8_2020.txt',
 'YumaAug18_2020.txt']

In [5]:
import pandas as pd

In [6]:
df = pd.DataFrame(index=range(len(noms_fichiers)), columns=['Nom_du_Fichier','Contenu'])
df.head()

  Nom_du_Fichier Contenu
0            NaN     NaN
1            NaN     NaN
2            NaN     NaN
3            NaN     NaN
4            NaN     NaN

In [7]:
for i,f_name in enumerate(noms_fichiers):
    f = open("Speeches/" + f_name, "r", encoding="utf-8")
    f_content = f.readlines()
    f.close()
    
    df.at[i, "Nom_du_Fichier"] = f_name
    df.at[i, "Contenu"] = f_content[0]

In [8]:
df.count()

Nom_du_Fichier    35
Contenu           35
dtype: int64

In [9]:
df

,Nom_du_Fichier,Contenu
0,BattleCreekDec19_2019.txt,Thank you. Thank you. Thank you to Vice Presid...
1,BemidjiSep18_2020.txt,There's a lot of people. That's great. Thank y...
2,CharlestonFeb28_2020.txt,Thank you. Thank you. Thank you. All I can say...
3,CharlotteMar2_2020.txt,"I want to thank you very much. North Carolina,..."
4,CincinnatiAug1_2019.txt,Thank you all. Thank you very much. Thank you ...
5,ColoradorSpringsFeb20_2020.txt,"Hello Colorado. We love Colorado, most beautif..."
6,DallasOct17_2019.txt,Thank you. Thank you very much. Hello Dallas. ...
7,DesMoinesJan30_2020.txt,I worked so hard for this state. I worked so h...
8,FayettevilleSep19_2020.txt,"What a crowd, what a crowd. Get those people o..."
9,FayettevilleSep9_2019.txt,Thank you everybody. Thank you and Vice Presi...
10,FreelandSep10_2020.txt,"We brought you a lot of car plants, Michigan. ..."
11,GreenvilleJul17_2019.txt,Thank you very much. Thank you. Thank you. Tha...
12,HendersonSep13_2020.txt,"Thank you, thank you. Wow. Wow, and I'm thrill..."
13,HersheyDec10_2019.txt,"Well, thank you to Vice President Pence. Than..."
14,LasVegasFeb21_2020.txt,"Well, thank you very much. And hello Las Vegas..."
15,LatrobeSep3_2020.txt,"So thank you Pennsylvania, very much. I'm thri..."
16,LexingtonNov4_2019.txt,Thank you very much and thank you to the origi...
17,MilwaukeeJan14_2020.txt,Well thank you very much. And I'm thrilled to ...
18,MindenSep12_2020.txt,"Well, I thank you very much. So I want to star..."
19,MinneapolisOct10_2019.txt,"Thank you very much. Thank you, Minnesota. Thi..."
20,MosineeSep17_2020.txt,"Thank you, thank you very much. Thank you very..."
21,NewHampshireAug15_2019.txt,Thank you very much everybody. Thank you. Wow...
22,NewHampshireAug28_2020.txt,"Hello, everybody. Hello, everybody. Wow. Hello..."
23,NewHampshireFeb10_2020.txt,"Hello, Manchester, and I am thrilled to be in ..."
24,NewMexicoSep16_2019.txt,"Wow, thank you. Thank you, New Mexico. Thank ..."
25,OhioSep21_2020.txt,"Wow, that's a big crowd. This is a big crowd. ..."
26,PhoenixFeb19_2020.txt,"Thank you very much, Phoenix. We love to be b..."
27,PittsburghSep22_2020.txt,Doesn't have the power. Doesn't have the stayi...
28,TexasSep23_2019.txt,"Hello, Houston. I am so thrilled to be here in..."
29,ToledoJan9_2020.txt,"Well, thank you very much. Vice President Mike..."
30,TulsaJun20_2020.txt,"Thank you, thank you. So we begin, Oklahoma, w..."
31,TupeloNov1_2019.txt,"ell, thank you very much. And hello, Tupelo. T..."
32,WildwoodJan28_2020.txt,Thank you. Thank you. I love New Jersey and I'...
33,Winston-SalemSep8_2020.txt,"Well, thank you very much. Thank you. Thank yo..."
34,YumaAug18_2020.txt,"Oh, thank you very much, everybody. Thank you...."

In [10]:
# Liste des mots possibles
mois = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
mois

['Jan',
 'Feb',
 'Mar',
 'Apr',
 'May',
 'Jun',
 'Jul',
 'Aug',
 'Sep',
 'Oct',
 'Nov',
 'Dec']

In [11]:
def SeparerVille(v):
    for m in mois:
        if (m in v):
            ville = v[:v.find(m)]
            return ville

In [12]:
# Application de la fonction SeparerVille()
df['Ville'] = df.Nom_du_Fichier.apply(SeparerVille)
df.head()

,Nom_du_Fichier,Contenu,Ville
0,BattleCreekDec19_2019.txt,Thank you. Thank you. Thank you to Vice Presid...,BattleCreek
1,BemidjiSep18_2020.txt,There's a lot of people. That's great. Thank y...,Bemidji
2,CharlestonFeb28_2020.txt,Thank you. Thank you. Thank you. All I can say...,Charleston
3,CharlotteMar2_2020.txt,"I want to thank you very much. North Carolina,...",Charlotte
4,CincinnatiAug1_2019.txt,Thank you all. Thank you very much. Thank you ...,Cincinnati

In [13]:
df.tail()

,Nom_du_Fichier,Contenu,Ville
30,TulsaJun20_2020.txt,"Thank you, thank you. So we begin, Oklahoma, w...",Tulsa
31,TupeloNov1_2019.txt,"ell, thank you very much. And hello, Tupelo. T...",Tupelo
32,WildwoodJan28_2020.txt,Thank you. Thank you. I love New Jersey and I'...,Wildwood
33,Winston-SalemSep8_2020.txt,"Well, thank you very much. Thank you. Thank yo...",Winston-Salem
34,YumaAug18_2020.txt,"Oh, thank you very much, everybody. Thank you....",Yuma

In [14]:
strtotal = "PapaMamanEnfant"

In [15]:
len("Papa")

4

In [16]:
strtotal[len("Papa"):-6]

'Maman'

In [17]:
strtotal[len("Papa"):-6]

'Maman'

In [18]:
strtotal.find("Enfant")

9

In [19]:
# On veut la portion "Maman"
strtotal[len("Papa"):strtotal.find("Enfant")]

'Maman'

In [20]:
def SeparerDate(c):
    date = c.Nom_du_Fichier[len(c.Ville):c.Nom_du_Fichier.find(".txt")]
    return date

In [21]:
df['Date'] = df.apply(SeparerDate, axis = 1)
df.head()

,Nom_du_Fichier,Contenu,Ville,Date
0,BattleCreekDec19_2019.txt,Thank you. Thank you. Thank you to Vice Presid...,BattleCreek,Dec19_2019
1,BemidjiSep18_2020.txt,There's a lot of people. That's great. Thank y...,Bemidji,Sep18_2020
2,CharlestonFeb28_2020.txt,Thank you. Thank you. Thank you. All I can say...,Charleston,Feb28_2020
3,CharlotteMar2_2020.txt,"I want to thank you very much. North Carolina,...",Charlotte,Mar2_2020
4,CincinnatiAug1_2019.txt,Thank you all. Thank you very much. Thank you ...,Cincinnati,Aug1_2019

In [22]:
df.dtypes

Nom_du_Fichier    object
Contenu           object
Ville             object
Date              object
dtype: object

In [23]:
df['Date'] = pd.to_datetime(df['Date'], format="%b%d_%Y")
df.head()

,Nom_du_Fichier,Contenu,Ville,Date
0,BattleCreekDec19_2019.txt,Thank you. Thank you. Thank you to Vice Presid...,BattleCreek,2019-12-19
1,BemidjiSep18_2020.txt,There's a lot of people. That's great. Thank y...,Bemidji,2020-09-18
2,CharlestonFeb28_2020.txt,Thank you. Thank you. Thank you. All I can say...,Charleston,2020-02-28
3,CharlotteMar2_2020.txt,"I want to thank you very much. North Carolina,...",Charlotte,2020-03-02
4,CincinnatiAug1_2019.txt,Thank you all. Thank you very much. Thank you ...,Cincinnati,2019-08-01

In [24]:
df.drop("Nom_du_Fichier", axis = 1, inplace = True)

In [25]:
df.head()

                                             Contenu        Ville       Date
0  Thank you. Thank you. Thank you to Vice Presid...  BattleCreek 2019-12-19
1  There's a lot of people. That's great. Thank y...      Bemidji 2020-09-18
2  Thank you. Thank you. Thank you. All I can say...   Charleston 2020-02-28
3  I want to thank you very much. North Carolina,...    Charlotte 2020-03-02
4  Thank you all. Thank you very much. Thank you ...   Cincinnati 2019-08-01

In [26]:
# Année
df['Année'] = df.Date.dt.year
# Mois
df['Mois'] = df.Date.dt.month
# Jour (Jour du mois)
df['Jour_du_mois'] = df.Date.dt.day
# Jour de la semaine (0 pour lundi et 6 pour dimanche)
df['Jour_de_la_semaine'] = df.Date.dt.weekday

df.head()

,Contenu,Ville,Date,Année,Mois,Jour_du_mois,Jour_de_la_semaine
0,Thank you. Thank you. Thank you to Vice Presid...,BattleCreek,2019-12-19,2019,12,19,3
1,There's a lot of people. That's great. Thank y...,Bemidji,2020-09-18,2020,9,18,4
2,Thank you. Thank you. Thank you. All I can say...,Charleston,2020-02-28,2020,2,28,4
3,"I want to thank you very much. North Carolina,...",Charlotte,2020-03-02,2020,3,2,0
4,Thank you all. Thank you very much. Thank you ...,Cincinnati,2019-08-01,2019,8,1,3

In [27]:
import numpy as np

In [28]:
df["Weekend"] = np.where((df.Jour_de_la_semaine == 5) | (df.Jour_de_la_semaine == 6), "Oui", "Non")
df

,Contenu,Ville,Date,Année,Mois,Jour_du_mois,Jour_de_la_semaine,Weekend
0,Thank you. Thank you. Thank you to Vice Presid...,BattleCreek,2019-12-19,2019,12,19,3,Non
1,There's a lot of people. That's great. Thank y...,Bemidji,2020-09-18,2020,9,18,4,Non
2,Thank you. Thank you. Thank you. All I can say...,Charleston,2020-02-28,2020,2,28,4,Non
3,"I want to thank you very much. North Carolina,...",Charlotte,2020-03-02,2020,3,2,0,Non
4,Thank you all. Thank you very much. Thank you ...,Cincinnati,2019-08-01,2019,8,1,3,Non
5,"Hello Colorado. We love Colorado, most beautif...",ColoradorSprings,2020-02-20,2020,2,20,3,Non
6,Thank you. Thank you very much. Hello Dallas. ...,Dallas,2019-10-17,2019,10,17,3,Non
7,I worked so hard for this state. I worked so h...,DesMoines,2020-01-30,2020,1,30,3,Non
8,"What a crowd, what a crowd. Get those people o...",Fayetteville,2020-09-19,2020,9,19,5,Oui
9,Thank you everybody. Thank you and Vice Presi...,Fayetteville,2019-09-09,2019,9,9,0,Non
10,"We brought you a lot of car plants, Michigan. ...",Freeland,2020-09-10,2020,9,10,3,Non
11,Thank you very much. Thank you. Thank you. Tha...,Greenville,2019-07-17,2019,7,17,2,Non
12,"Thank you, thank you. Wow. Wow, and I'm thrill...",Henderson,2020-09-13,2020,9,13,6,Oui
13,"Well, thank you to Vice President Pence. Than...",Hershey,2019-12-10,2019,12,10,1,Non
14,"Well, thank you very much. And hello Las Vegas...",LasVegas,2020-02-21,2020,2,21,4,Non
15,"So thank you Pennsylvania, very much. I'm thri...",Latrobe,2020-09-03,2020,9,3,3,Non
16,Thank you very much and thank you to the origi...,Lexington,2019-11-04,2019,11,4,0,Non
17,Well thank you very much. And I'm thrilled to ...,Milwaukee,2020-01-14,2020,1,14,1,Non
18,"Well, I thank you very much. So I want to star...",Minden,2020-09-12,2020,9,12,5,Oui
19,"Thank you very much. Thank you, Minnesota. Thi...",Minneapolis,2019-10-10,2019,10,10,3,Non
20,"Thank you, thank you very much. Thank you very...",Mosinee,2020-09-17,2020,9,17,3,Non
21,Thank you very much everybody. Thank you. Wow...,NewHampshire,2019-08-15,2019,8,15,3,Non
22,"Hello, everybody. Hello, everybody. Wow. Hello...",NewHampshire,2020-08-28,2020,8,28,4,Non
23,"Hello, Manchester, and I am thrilled to be in ...",NewHampshire,2020-02-10,2020,2,10,0,Non
24,"Wow, thank you. Thank you, New Mexico. Thank ...",NewMexico,2019-09-16,2019,9,16,0,Non
25,"Wow, that's a big crowd. This is a big crowd. ...",Ohio,2020-09-21,2020,9,21,0,Non
26,"Thank you very much, Phoenix. We love to be b...",Phoenix,2020-02-19,2020,2,19,2,Non
27,Doesn't have the power. Doesn't have the stayi...,Pittsburgh,2020-09-22,2020,9,22,1,Non
28,"Hello, Houston. I am so thrilled to be here in...",Texas,2019-09-23,2019,9,23,0,Non
29,"Well, thank you very much. Vice President Mike...",Toledo,2020-01-09,2020,1,9,3,Non
30,"Thank you, thank you. So we begin, Oklahoma, w...",Tulsa,2020-06-20,2020,6,20,5,Oui
31,"ell, thank you very much. And hello, Tupelo. T...",Tupelo,2019-11-01,2019,11,1,4,Non
32,Thank you. Thank you. I love New Jersey and I'...,Wildwood,2020-01-28,2020,1,28,1,Non
33,"Well, thank you very much. Thank you. Thank yo...",Winston-Salem,2020-09-08,2020,9,8,1,Non
34,"Oh, thank you very much, everybody. Thank you....",Yuma,2020-08-18,2020,8,18,1,Non

In [29]:
df.to_csv("cleaned-speeches.csv", index=False)